### ISSUE TITLE
raphael.js error: Uncaught TypeError: Cannot read properties of undefined (reading 'on')

### ISSUE THREAD

**Issue by jiamliang** [ForbesLindesay/regexplained#2]
I want to use this code in my React project. 

```
import regexplained from 'regexplained';
// other codes ....
  useEffect(() => {
    console.log(regexplained);
  }, []);
```
Error in console:

Uncaught TypeError: Cannot read properties of undefined (reading 'on')
    at raphael.js:5216:1
    at Object.<anonymous> (raphael.js:393:1)
    at raphael.js:394:1
    at ./node_modules/regexplained/node_modules/raphael/raphael.js (raphael.js:400:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:22:1)
    at fn (hot module replacement:61:1)
    at ./node_modules/regexplained/lib/renderer.js (renderer.js:1:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:22:1)

**Comment by jiamliang** [comment]
[    "raphael": "~2.1.0"](https://github.com/ForbesLindesay/regexplained/blob/7db6e649c173cea3619c0bbefeda0254ca32d569/package.json#L7)

change to version 2.3.0 solve this problem in my case.
